---
name: reports-check
on:
 issues:
   types: opened
jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: tracehubpm/reports-check-action@0.1.1-deepinfra
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          deepinfra_token: ${{ secrets.DEEPINFRA_TOKEN }}
